server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my360_jugezhuang?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root


