server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my360_comwinwin?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root





