server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/g_template?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root





